SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'stg'
  AND TABLE_NAME IN (
        'WaterConsumption_Translation_2021_2022',
        'WaterConsumption_Translation_2023_2025'
  )
ORDER BY
    TABLE_NAME,
    ORDINAL_POSITION;
